### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by yangzhou6666** [goutham7r/backdoors-for-code#1]
Thanks for making the code open source!

I manage to run the pipeline (from preprocessing and model evaluation). But I found that the models I obtained have lower performance on the clean dataset. 

I think that this is caused by the datasets. As the guideline to prepare datasets is missing, I use the dataset from [averloc](https://github.com/jjhenkel/averloc), and do some necessary processing (e.g., adding indexes, etc). 

But the training data size I use is around 150k, smaller than the number reported in this backdoor attack paper (Table 4 says the training data is over 400k). So this can be the reason why models on my side perform worse.

Could you provide some details about the dataset you use? for example, the url, etc. 

Thanks!

**Comment by goutham7r** [comment]
The datasets we used were derived from code2seq's java-small (https://github.com/tech-srl/code2seq) and the python dataset from Github’s CodeSearchNet (https://github.com/github/CodeSearchNet). For the averloc project, we had to use a subset of the data due to computational limitations.
